version: "3.9"
services:
  database:
    container_name: database
    image: postgres:12
    pull_policy: missing
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U directus" ]
      interval: 3s
      timeout: 5s
      retries: 10

  #  pgadmin:
  #    container_name: pgadmin
  #    image: dpage/pgadmin4
  #    restart: always
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #      PGADMIN_DEFAULT_PASSWORD: root
  #    ports:
  #      - "5050:80"
  #    depends_on:
  #      database:
  #        condition: service_healthy

  cache:
    container_name: cache
    image: redis

  directus:
    container_name: api
    image: directus-custom-endpoint
    restart: "always"
    ports:
      - "8055:8055"
    volumes:
      - "./data/directus/uploads:/directus/uploads"
      - "./data/directus/logs:/directus/logs"
      - "./extensions:/directus/extensions"
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_started
    environment:
      EXTENSIONS_AUTO_RELOAD: ${DIRECTUS_EXTENSIONS_AUTO_RELOAD}
      DIRECTUS_LOG_LEVEL: ${DIRECTUS_LOG_LEVEL}
      DIRECTUS_LOG_STYLE: ${DIRECTUS_LOG_STYLE}
      PUBLIC_URL: ${DIRECTUS_PUBLIC_URL}
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      DB_CLIENT: ${DIRECTUS_DB_CLIENT}
      DB_HOST: ${DIRECTUS_DB_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      CACHE_ENABLED: ${DIRECTUS_CACHE_ENABLE}
      CACHE_STORE: ${DIRECTUS_CACHE_STORE}
      CACHE_REDIS: ${DIRECTUS_CACHE_REDIS}
